# Generated by Django 6.0.8 on 2026-08-09 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_region_remove_zone_created_at_alter_zone_zone_name_and_more'),
        ('shipping_bill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingbill',
            name='bl_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='bl_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='container_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='customs_assessment_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='customs_house_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='egm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='egm_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='exporter_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='let_export_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='mode_of_transport',
            field=models.CharField(default='SEA', max_length=30),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='physical_copies_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='port_of_discharge',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='port_of_loading',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='proof_of_export_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='proof_of_export_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='request_id',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='shipment_success_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='shipping_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='supporting_documents_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='voyage_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_bills', to='company.company'),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='consignee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shipping_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='destination_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='exporter_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='shipping_bill_no',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_APPROVER', 'Submitted to Unit Approver'), ('SENT_BACK', 'Sent Back to Unit Maker'), ('CANCELLED', 'Cancelled'), ('SUBMITTED_TO_CUSTOMS', 'Submitted to DC Customs'), ('QUERY_RAISED', 'Query Raised'), ('QUERY_FORWARDED', 'Query Forwarded to Unit Maker'), ('QUERY_RESPONDED', 'Query Responded'), ('LET_EXPORT', 'Let Export'), ('EGM_SUBMITTED', 'EGM Submitted'), ('SHIPMENT_SUCCESS', 'Shipment Success'), ('PROOF_OF_EXPORT', 'Proof of Export')], default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='total_invoice_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='ShippingBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ritc_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('unit_of_measurement', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping_bill.shippingbill')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingBillQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('forwarded_to_maker', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_queries_raised', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_queries_answered', to=settings.AUTH_USER_MODEL)),
                ('shipping_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='shipping_bill.shippingbill')),
            ],
        ),
    ]
