# Generated by Django 6.0.8 on 2026-08-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_bill', '0002_shippingbill_bl_date_shippingbill_bl_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingbillquery',
            name='approver_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
