# Generated by Django 6.0.8 on 2026-08-11 14:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_bill', '0003_shippingbillquery_approver_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingbill',
            name='ac_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='approver_submitted_to_ac_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='destination_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='destination_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='post_let_document',
            field=models.FileField(blank=True, null=True, upload_to='shipping_bill_post_let/'),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='post_let_document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingbill',
            name='seal_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='calculated_igst',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='calculated_other_duty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='export_duty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='other_duty_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='risk_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='total_tax_duty_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_APPROVER', 'Submitted to Unit Approver'), ('SENT_BACK', 'Sent Back to Unit Maker'), ('CANCELLED', 'Cancelled'), ('SUBMITTED_TO_CUSTOMS', 'Submitted to DC Customs'), ('QUERY_RAISED', 'Query Raised'), ('QUERY_FORWARDED', 'Query Forwarded to Unit Maker'), ('QUERY_RESPONDED', 'Query Responded'), ('LET_EXPORT', 'Let Export'), ('LET_EXPORT_PENDING_APPROVER', 'Let Export - Pending Unit Approver'), ('SUBMITTED_TO_AC', 'Submitted to AC Customs'), ('EGM_SUBMITTED', 'EGM Submitted'), ('SHIPMENT_SUCCESS', 'Shipment Success'), ('PROOF_OF_EXPORT', 'Proof of Export')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='shipping_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping_bill.shippingbill'),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='ShippingBillInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shipping_bill.shippingbill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shippingbillitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping_bill.shippingbillinvoice'),
        ),
        migrations.CreateModel(
            name='ShippingBillDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE_PACKAGE', 'Invoice Package'), ('BL_DOCUMENT', 'BL Document')], max_length=30)),
                ('file', models.FileField(upload_to='shipping_bill_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by_approver', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('shipping_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipping_bill.shippingbill')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_bill_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shipping_bill_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('shipping_bill', 'document_type'), name='unique_shipping_bill_document_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='shippingbillinvoice',
            constraint=models.UniqueConstraint(fields=('shipping_bill', 'invoice_number'), name='unique_invoice_number_per_shipping_bill'),
        ),
    ]
