# Generated by Django 6.0.8 on 2026-08-11 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_bill', '0004_shippingbill_ac_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingbilldocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shippingbillinvoice',
            options={},
        ),
        migrations.AlterField(
            model_name='shippingbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_TO_APPROVER', 'Submitted to Unit Approver'), ('SENT_BACK', 'Sent Back to Unit Maker'), ('CANCELLED', 'Cancelled'), ('SUBMITTED_TO_CUSTOMS', 'Submitted to DC Customs'), ('QUERY_RAISED', 'Query Raised'), ('QUERY_FORWARDED', 'Query Forwarded to Unit Maker'), ('QUERY_RESPONDED', 'Query Responded'), ('MAKER_RESPONDED', 'Maker Responded'), ('LET_EXPORT', 'Let Export'), ('SUBMITTED_TO_AC', 'Submitted to AC Customs'), ('EGM_SUBMITTED', 'EGM Submitted'), ('SHIPMENT_SUCCESS', 'Shipment Success'), ('PROOF_OF_EXPORT', 'Proof of Export')], default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='shippingbilldocument',
            name='document_type',
            field=models.CharField(choices=[('INVOICE_PACKAGE', 'Invoice Package'), ('BL_DOCUMENT', 'Bill of Lading Document')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shippingbilldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_shipping_bill_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippingbillinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingbillinvoice',
            name='total_invoice_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='calculated_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='calculated_other_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='other_duty_rate',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='total_tax_duty_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shippingbillitem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
