# Generated by Django 6.0.8 on 2026-08-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('company', '0002_region_remove_zone_created_at_alter_zone_zone_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_customs_users', to='company.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_customs_users', to='company.zone'),
        ),
    ]
